### PR TITLE
fixed bug in particles and added support for compressible flow in yaml

### LINKED ISSUE #48: Particles.cpp does not call the particle destroy.

### LINKED ISSUE #51: Explose compressible flow in yaml parser

### PR DESCRIPTION
**Pull request by mmcgurn**
addresses and closes #51 and closes #48

### CODE REVIEW

File: ablateCore/flow/compressibleFlow.c [hunk 1]
```diff
@@ -100,37 +100,37 @@ void CompressibleFlowComputeEulerFlux(PetscInt dim, PetscInt Nf, const PetscReal
...
-PetscErrorCode CompressibleFlow_SetupDiscretization(FlowData flowData, DM dm) {
+PetscErrorCode CompressibleFlow_SetupDiscretization(FlowData flowData, DM* dm) {
     PetscInt dim;
     PetscErrorCode ierr;
 
     PetscFunctionBeginUser;
-    ierr = DMSetFromOptions(dm);CHKERRQ(ierr);
+    ierr = DMSetFromOptions(*dm);CHKERRQ(ierr);
     const PetscInt ghostCellDepth = 1;
     {// Make sure that the flow is setup distributed
```
Comment (knepley) [inline ablateCore/flow/compressibleFlow.c:110]: I have an MR allowing all this crud to be done in options. I hope to have it in less then 2 weeks from now.

**Review by knepley — APPROVED** [review]
Looks good. Can't wait to see the compressible results.
